import React from 'react'
import PropTypes from 'prop-types'
import Head from 'next/head'
import Header from '../../components/header/header'
import styles from './layout.module.css'


export default function Layout(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Skip Gibson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />
      { props.children }
    </div>
  )
}

Layout.propTypes = {
  children: PropTypes.node,
}
