import Head from 'next/head'
import Layout from '../components/layout/layout'
import Header from '../components/header/header'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Skip Gibson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />
    </Layout>
  )
}
